Security Vulnerabilities fixes
hps/heartland-wordpress-management-terminal-plugin pull request #12
Opened 2024-12-12 13:36 UTC by mayur-vachchewar

- Security Vulnerabilities issues fix initial commit

2024-12-17 16:53 UTC, MSmedal requested changes

2024-12-17 16:53 UTC, MSmedal commented on classes/includes/src/Entities/Credit/HpsReportTransactionSummary.php
> +                || (isset($isserResponseCode) && $isserResponseCode !== null && $issuerResponseCode != "00")
`isset($isserResponseCode) && $isserResponseCode !== null` seems to be redundant

2024-12-17 16:53 UTC, MSmedal commented on classes/includes/src/Entities/Credit/HpsReportTransactionSummary.php
> +                if (isset($isserResponseCode) && $isserResponseCode !== null && $issuerResponseCode != "00") {
same here

2024-12-19 17:45 UTC, MSmedal approved these changes

2025-01-14 15:25 UTC, MSmedal commented on classes/includes/src/Abstractions/HpsGatewayServiceAbstract.php
@mayur-vachchewar what is the reason for reverting back to curl options in this file?

2025-01-14 15:26 UTC, MSmedal requested changes
please advise on my latest comment

2025-01-15 10:04 UTC, mayur-vachchewar commented on classes/includes/src/Abstractions/HpsGatewayServiceAbstract.php
As discussed I have added WordPress based functionality to replace CuRL. Please review once.

2025-01-16 03:00 UTC, MSmedal approved these changes

2025-01-21 13:23 UTC, merged